import { z } from "zod";

const MilestoneStatusValues = [
  "PENDING",
  "IN_PROGRESS",
  "COMPLETED",
  "MISSED",
  "WAIVED",
  "NOT_APPLICABLE",
] as const;

// ============================================
// MILESTONE SCHEMAS
// ============================================

export const milestoneCreateSchema = z.object({
  timelineId: z.string().cuid("Invalid timeline ID"),
  name: z.string().min(1, "Milestone name is required").max(200),
  description: z.string().max(2000).optional(),
  dueDate: z.coerce.date(),
  parentId: z.string().cuid().optional().nullable(),
  reminderDays: z.array(z.number().int().positive().max(365)).max(5).optional(),
});

export const milestoneUpdateSchema = milestoneCreateSchema.partial().omit({ timelineId: true }).extend({
  status: z.enum(MilestoneStatusValues).optional(),
  completedDate: z.coerce.date().optional().nullable(),
});

export const milestoneFilterSchema = z.object({
  dealId: z.string().cuid().optional(),
  timelineId: z.string().cuid().optional(),
  status: z.union([z.enum(MilestoneStatusValues), z.array(z.enum(MilestoneStatusValues))]).optional(),
  dueDateFrom: z.coerce.date().optional(),
  dueDateTo: z.coerce.date().optional(),
  isOverdue: z.boolean().optional(),
  isAutoGenerated: z.boolean().optional(),
});

export type MilestoneCreateInput = z.infer<typeof milestoneCreateSchema>;
export type MilestoneUpdateInput = z.infer<typeof milestoneUpdateSchema>;
export type MilestoneFilterInput = z.infer<typeof milestoneFilterSchema>;
