"use client";

import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import type { MilestoneStatus } from "@/types/prisma";

interface Milestone {
  id: string;
  name: string;
  description?: string | null;
  dueDate: string;
  completedDate?: string | null;
  status: MilestoneStatus;
  isAutoGenerated: boolean;
  children?: Milestone[];
  tasks?: { id: string; title: string; status: string }[];
  createdAt: string;
  updatedAt: string;
}

interface TimelineResponse {
  timeline: { id: string } | null;
  milestones: Milestone[];
}

interface CreateMilestoneInput {
  name: string;
  description?: string;
  dueDate: string;
  parentId?: string | null;
  reminderDays?: number[];
}

interface UpdateMilestoneInput extends Partial<CreateMilestoneInput> {
  status?: MilestoneStatus;
  completedDate?: string | null;
}

async function fetchMilestones(dealId: string): Promise<TimelineResponse> {
  const res = await fetch(`/api/deals/${dealId}/milestones`);
  if (!res.ok) throw new Error("Failed to fetch milestones");
  return res.json();
}

async function createMilestone(dealId: string, data: CreateMilestoneInput): Promise<Milestone> {
  const res = await fetch(`/api/deals/${dealId}/milestones`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(data),
  });
  if (!res.ok) throw new Error("Failed to create milestone");
  return res.json();
}

async function updateMilestone(dealId: string, milestoneId: string, data: UpdateMilestoneInput): Promise<Milestone> {
  const res = await fetch(`/api/deals/${dealId}/milestones/${milestoneId}`, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(data),
  });
  if (!res.ok) throw new Error("Failed to update milestone");
  return res.json();
}

async function deleteMilestone(dealId: string, milestoneId: string): Promise<void> {
  const res = await fetch(`/api/deals/${dealId}/milestones/${milestoneId}`, {
    method: "DELETE",
  });
  if (!res.ok) throw new Error("Failed to delete milestone");
}

export function useMilestones(dealId: string) {
  return useQuery({
    queryKey: ["milestones", dealId],
    queryFn: () => fetchMilestones(dealId),
    enabled: !!dealId,
  });
}

export function useMilestoneMutations(dealId: string) {
  const queryClient = useQueryClient();

  const create = useMutation({
    mutationFn: (data: CreateMilestoneInput) => createMilestone(dealId, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["milestones", dealId] });
    },
  });

  const update = useMutation({
    mutationFn: ({ milestoneId, data }: { milestoneId: string; data: UpdateMilestoneInput }) =>
      updateMilestone(dealId, milestoneId, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["milestones", dealId] });
    },
  });

  const remove = useMutation({
    mutationFn: (milestoneId: string) => deleteMilestone(dealId, milestoneId),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["milestones", dealId] });
    },
  });

  return { create, update, remove };
}
