import type {
  DealType,
  DealStatus,
  PropertyType,
  TaskStatus,
  TaskPriority,
  DocumentCategory,
  MilestoneStatus,
} from "@/types/prisma";

// ============================================
// SORTING
// ============================================

export type SortDirection = "asc" | "desc";

export interface SortOption<T extends string = string> {
  field: T;
  direction: SortDirection;
}

// ============================================
// DEAL FILTERS
// ============================================

export interface DealFilters {
  search?: string;
  status?: DealStatus | DealStatus[];
  type?: DealType;
  propertyType?: PropertyType | PropertyType[];
  clientId?: string;
  createdById?: string;
  propertyState?: string;
  propertyCity?: string;
  closingDateFrom?: Date;
  closingDateTo?: Date;
  createdAtFrom?: Date;
  createdAtTo?: Date;
}

export type DealSortField =
  | "name"
  | "dealNumber"
  | "status"
  | "createdAt"
  | "updatedAt"
  | "closingDate"
  | "propertyCity"
  | "propertyState";

export interface DealListParams {
  filters?: DealFilters;
  sort?: SortOption<DealSortField>;
  page?: number;
  limit?: number;
}

// ============================================
// TASK FILTERS
// ============================================

export interface TaskFilters {
  search?: string;
  status?: TaskStatus | TaskStatus[];
  priority?: TaskPriority | TaskPriority[];
  dealId?: string;
  assigneeId?: string;
  createdById?: string;
  milestoneId?: string;
  category?: string;
  tags?: string[];
  dueDateFrom?: Date;
  dueDateTo?: Date;
  isOverdue?: boolean;
  hasAssignee?: boolean;
}

export type TaskSortField =
  | "title"
  | "status"
  | "priority"
  | "dueDate"
  | "createdAt"
  | "updatedAt"
  | "sortOrder";

export interface TaskListParams {
  filters?: TaskFilters;
  sort?: SortOption<TaskSortField>;
  page?: number;
  limit?: number;
  includeSubtasks?: boolean;
}

// ============================================
// DOCUMENT FILTERS
// ============================================

export interface DocumentFilters {
  search?: string;
  category?: DocumentCategory | DocumentCategory[];
  dealId?: string;
  folderId?: string;
  uploadedById?: string;
  fileType?: string;
  isAnalyzed?: boolean;
  isPrimaryContract?: boolean;
  createdAtFrom?: Date;
  createdAtTo?: Date;
}

export type DocumentSortField =
  | "name"
  | "category"
  | "fileSize"
  | "createdAt"
  | "updatedAt"
  | "sortOrder";

export interface DocumentListParams {
  filters?: DocumentFilters;
  sort?: SortOption<DocumentSortField>;
  page?: number;
  limit?: number;
}

// ============================================
// NOTE FILTERS
// ============================================

export interface NoteFilters {
  search?: string;
  dealId?: string;
  authorId?: string;
  category?: string;
  tags?: string[];
  isPinned?: boolean;
  createdAtFrom?: Date;
  createdAtTo?: Date;
}

export type NoteSortField = "title" | "createdAt" | "updatedAt" | "isPinned";

export interface NoteListParams {
  filters?: NoteFilters;
  sort?: SortOption<NoteSortField>;
  page?: number;
  limit?: number;
}

// ============================================
// MILESTONE FILTERS
// ============================================

export interface MilestoneFilters {
  dealId?: string;
  timelineId?: string;
  status?: MilestoneStatus | MilestoneStatus[];
  dueDateFrom?: Date;
  dueDateTo?: Date;
  isOverdue?: boolean;
  isAutoGenerated?: boolean;
}

export type MilestoneSortField = "name" | "dueDate" | "status" | "sortOrder" | "createdAt";

export interface MilestoneListParams {
  filters?: MilestoneFilters;
  sort?: SortOption<MilestoneSortField>;
  page?: number;
  limit?: number;
}

// ============================================
// NOTIFICATION FILTERS
// ============================================

export interface NotificationFilters {
  isRead?: boolean;
  type?: string;
  entityType?: string;
  createdAtFrom?: Date;
  createdAtTo?: Date;
}

export interface NotificationListParams {
  filters?: NotificationFilters;
  page?: number;
  limit?: number;
}

// ============================================
// ACTIVITY LOG FILTERS
// ============================================

export interface ActivityLogFilters {
  userId?: string;
  dealId?: string;
  action?: string;
  entityType?: string;
  entityId?: string;
  createdAtFrom?: Date;
  createdAtTo?: Date;
}

export interface ActivityLogListParams {
  filters?: ActivityLogFilters;
  page?: number;
  limit?: number;
}

// ============================================
// CLIENT FILTERS
// ============================================

export interface ClientFilters {
  search?: string;
  firmId?: string;
  type?: string;
}

export type ClientSortField = "name" | "createdAt" | "updatedAt";

export interface ClientListParams {
  filters?: ClientFilters;
  sort?: SortOption<ClientSortField>;
  page?: number;
  limit?: number;
}

// ============================================
// USER FILTERS
// ============================================

export interface UserFilters {
  search?: string;
  role?: string;
  status?: string;
  firmId?: string;
  clientId?: string;
}

export type UserSortField = "name" | "email" | "role" | "createdAt" | "lastLoginAt";

export interface UserListParams {
  filters?: UserFilters;
  sort?: SortOption<UserSortField>;
  page?: number;
  limit?: number;
}
