// Local model type definitions
// These match the Prisma schema models and are used when @prisma/client types aren't available

import type {
  UserRole,
  UserStatus,
  DealType,
  DealStatus,
  PropertyType,
  TaskStatus,
  TaskPriority,
  MilestoneStatus,
  DocumentCategory,
  DepositStatus,
} from "./prisma";

// ============================================
// USER MODELS
// ============================================

export interface User {
  id: string;
  email: string;
  name: string;
  passwordHash?: string | null;
  role: UserRole;
  status: UserStatus;
  avatar?: string | null;
  phone?: string | null;
  title?: string | null;
  emailVerified?: Date | null;
  firmId?: string | null;
  clientId?: string | null;
  createdAt: Date;
  updatedAt: Date;
  lastLoginAt?: Date | null;
}

export interface Firm {
  id: string;
  name: string;
  address?: string | null;
  phone?: string | null;
  website?: string | null;
  logo?: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface Client {
  id: string;
  name: string;
  type?: string | null;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  website?: string | null;
  firmId: string;
  createdAt: Date;
  updatedAt: Date;
}

// ============================================
// DEAL MODELS
// ============================================

export interface Deal {
  id: string;
  name: string;
  dealNumber: string;
  type: DealType;
  status: DealStatus;
  propertyName?: string | null;
  propertyType?: PropertyType | null;
  propertyAddress?: string | null;
  propertyCity?: string | null;
  propertyState?: string | null;
  propertyZip?: string | null;
  propertyCounty?: string | null;
  acreage?: number | null;
  squareFootage?: number | null;
  lotCount?: number | null;
  unitCount?: number | null;
  assessorPin?: string | null;
  assessorReportUrl?: string | null;
  propertyImageUrl?: string | null;
  clientId: string;
  createdById: string;
  createdAt: Date;
  updatedAt: Date;
  closedAt?: Date | null;
}

export interface TransactionSummary {
  id: string;
  dealId: string;
  contractDate?: Date | null;
  effectiveDate?: Date | null;
  buyerName?: string | null;
  buyerEntity?: string | null;
  buyerAddress?: string | null;
  sellerName?: string | null;
  sellerEntity?: string | null;
  sellerAddress?: string | null;
  purchasePrice?: number | null;
  pricePerUnit?: number | null;
  priceAdjustable: boolean;
  priceAdjustmentBasis?: string | null;
  initialDeposit?: number | null;
  initialDepositDue?: Date | null;
  additionalDeposits?: unknown;
  feasibilityPeriodDays?: number | null;
  feasibilityExpiration?: Date | null;
  closingDate?: Date | null;
  outsideClosingDate?: Date | null;
  contingencies?: unknown;
  dueDiligenceItems?: unknown;
  closingDocuments?: unknown;
  specialProvisions?: unknown;
  titleCompany?: string | null;
  escrowAgent?: string | null;
  surveyRequirements?: string | null;
  prorationDate?: Date | null;
  prorationItems?: unknown;
  rawAnalysis?: unknown;
  version: number;
  analyzedAt: Date;
  analyzedFromDocId?: string | null;
  createdAt: Date;
  updatedAt: Date;
}

// ============================================
// TIMELINE MODELS
// ============================================

export interface Timeline {
  id: string;
  dealId: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Milestone {
  id: string;
  timelineId: string;
  parentId?: string | null;
  name: string;
  description?: string | null;
  dueDate: Date;
  completedDate?: Date | null;
  status: MilestoneStatus;
  isAutoGenerated: boolean;
  sourceType?: string | null;
  sourceReference?: string | null;
  sortOrder: number;
  reminderDays: number[];
  createdAt: Date;
  updatedAt: Date;
}

// ============================================
// TASK MODELS
// ============================================

export interface Task {
  id: string;
  dealId: string;
  milestoneId?: string | null;
  parentId?: string | null;
  title: string;
  description?: string | null;
  status: TaskStatus;
  priority: TaskPriority;
  dueDate?: Date | null;
  startDate?: Date | null;
  completedAt?: Date | null;
  assigneeId?: string | null;
  createdById: string;
  category?: string | null;
  tags: string[];
  customFields?: unknown;
  sortOrder: number;
  estimatedHours?: number | null;
  actualHours?: number | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface TaskChecklist {
  id: string;
  taskId: string;
  name: string;
  sortOrder: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface TaskChecklistItem {
  id: string;
  checklistId: string;
  text: string;
  isCompleted: boolean;
  completedAt?: Date | null;
  sortOrder: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface TaskComment {
  id: string;
  taskId: string;
  authorId: string;
  content: string;
  createdAt: Date;
  updatedAt: Date;
}

// ============================================
// DOCUMENT MODELS
// ============================================

export interface Document {
  id: string;
  dealId: string;
  folderId?: string | null;
  name: string;
  originalName: string;
  description?: string | null;
  category: DocumentCategory;
  subcategory?: string | null;
  fileType: string;
  fileSize: number;
  fileUrl: string;
  fileKey: string;
  version: number;
  previousVersionId?: string | null;
  uploadedById: string;
  isAnalyzed: boolean;
  isPrimaryContract: boolean;
  sortOrder: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface DocumentFolder {
  id: string;
  dealId: string;
  parentId?: string | null;
  name: string;
  description?: string | null;
  sortOrder: number;
  createdAt: Date;
  updatedAt: Date;
}

// ============================================
// NOTE MODELS
// ============================================

export interface Note {
  id: string;
  dealId: string;
  authorId: string;
  title?: string | null;
  content: string;
  plainText?: string | null;
  isPinned: boolean;
  category?: string | null;
  tags: string[];
  createdAt: Date;
  updatedAt: Date;
}

// ============================================
// FINANCIAL MODELS
// ============================================

export interface DealFinancials {
  id: string;
  dealId: string;
  contractPrice?: number | null;
  currentPrice?: number | null;
  dueDiligenceBudget?: number | null;
  dueDiligenceSpent?: number | null;
  estimatedClosingCosts?: number | null;
  actualClosingCosts?: number | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface Deposit {
  id: string;
  financialsId: string;
  name: string;
  amount: number;
  dueDate: Date;
  status: DepositStatus;
  paidDate?: Date | null;
  paidAmount?: number | null;
  condition?: string | null;
  notes?: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface FinancialLineItem {
  id: string;
  financialsId: string;
  category: string;
  name: string;
  description?: string | null;
  estimatedAmount?: number | null;
  actualAmount?: number | null;
  vendor?: string | null;
  invoiceNumber?: string | null;
  paidDate?: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

// ============================================
// NOTIFICATION MODELS
// ============================================

export interface Notification {
  id: string;
  userId: string;
  type: string;
  title: string;
  message: string;
  link?: string | null;
  isRead: boolean;
  readAt?: Date | null;
  entityType?: string | null;
  entityId?: string | null;
  createdAt: Date;
}

export interface UserPreferences {
  id: string;
  userId: string;
  emailNotifications: boolean;
  taskReminders: boolean;
  deadlineAlerts: boolean;
  notificationFrequency: string;
  dailySummaryTime?: string | null;
  weeklySummaryDay?: number | null;
  defaultDealView: string;
  defaultTaskView: string;
  timezone: string;
  dateFormat: string;
  createdAt: Date;
  updatedAt: Date;
}

// ============================================
// ACTIVITY LOG MODELS
// ============================================

export interface ActivityLog {
  id: string;
  userId?: string | null;
  dealId?: string | null;
  action: string;
  entityType: string;
  entityId: string;
  entityName?: string | null;
  changes?: unknown;
  metadata?: unknown;
  ipAddress?: string | null;
  userAgent?: string | null;
  createdAt: Date;
}
